version: "3"
services:

  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --reload-on-changes --working-directory ./main ./isa/wsgi.py"

networks:
  backend: